backend:
  name: git-gateway
  branch: master 

# logo_url: https://edinburghtailoredtours.com/img/favicon.jpg

media_folder: "fuck"
public_folder: "fuck"

collections:

  - label: "Pages"
    name: "pages"
    editor:
      preview: false
    files:
      - label: "Home page"
        name: "content"
        file: "content.yml"
        fields:
          - {label: "Title", name: "title", widget: "hidden", default: "content"}
          - {label: Site headline, name: siteHeadline, widget: string}






  # - label: "Pages"
  #   name: "pages"

  #   delete: false
  #   editor:
  #     preview: false
  #   slug: "{{slug}}"
  #   files:
  #     - label: "Home page"
  #       name: "home"
  #       fields:

  #         - {label: "Title", name: "title", widget: "hidden", default: "content"}

  #         - {label: Site headline, name: siteHeadline, widget: string}
  #         - {label: Site subheadline, name: siteSubheadline, widget: string}

  #         - {label: Kicker (left panel), name: offering1Kicker, widget: string}
  #         - {label: Headline (left panel), name: offering1Headline, widget: string}
  #         - {label: Description (left panel), name: offering1Description, widget: string}

  #         - {label: Kicker (right panel), name: offering2Kicker, widget: string}
  #         - {label: Headline (right panel), name: offering2Headline, widget: string}
  #         - {label: Description (right panel), name: offering2Description, widget: string}

  #         - {label: Review (left), name: review1Text, widget: string}
  #         - {label: Citation (left), name: review1Citation, widget: string}

  #         - {label: Review (centre), name: review2Text, widget: string}
  #         - {label: Citation (centre), name: review2Citation, widget: string}

  #         - {label: Review (right), name: review3Text, widget: string}
  #         - {label: Citation (right), name: review3Citation, widget: string}

  #         - {label: Enquiry panel headline, name: enquiryTitle, widget: string}
  #         - {label: Enquiry panel description, name: enquiryDescription, widget: string}

  #         - {label: Address, name: address, widget: string}
  #         - {label: Phone, name: phone, widget: string}
  #         - {label: Email, name: email, widget: string}

  #         - {label: Facebook, name: facebook, widget: string}
  #         - {label: Instagram, name: instagram, widget: string}
  #         - {label: Twitter, name: twitter, widget: string}

  #         - {label: Website description, hint: "This may appear in search engine results", name: siteDescription, widget: string}