backend:
  name: git-gateway
  branch: master 

media_folder: "src/img"
public_folder: "/dist/img"

collections:
  - label: "Pages"
    name: "pages"
    files:
      - label: "Home page"
        name: "home"
        file: "./content.yml"
        fields:
          - {label: Title, name: title, widget: string}